# Write your MySQL query statement below
WITH CTE AS 
(
  SELECT LAT,LON
   FROM INSURANCE
   GROUP BY 1,2
   HAVING COUNT(*) > 1
),
CTE2 AS (
    SELECT TIV_2015 AS TIV
    FROM INSURANCE
    GROUP BY 1
    HAVING COUNT(*) > 1
)
SELECT ROUND(SUM(tiv_2016),2) AS tiv_2016   
    FROM INSURANCE I LEFT OUTER JOIN CTE ON (I.LAT = CTE.LAT AND I.LON = CTE.LON)
    LEFT OUTER JOIN CTE2 ON I.TIV_2015 = TIV
    WHERE CTE.LAT IS NULL AND CTE.LON IS NULL AND TIV IS NOT NULL;
